In [38]:
%load_ext autoreload
%autoreload 2

import sys

sys.path.append("../")

print("Setup complete.")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Setup complete.


In [51]:
import numpy as np
from darth import fn
from darth.nn import Linear, Sequential
import darth.fn.activation as fav

In [52]:
vars(fav)

{'__name__': 'darth.fn.activation',
 '__doc__': '\nGeneric activation fn and class that works on any input shape\n',
 '__package__': 'darth.fn',
 '__loader__': <_frozen_importlib_external.SourceFileLoader at 0x181eeb16570>,
 '__spec__': ModuleSpec(name='darth.fn.activation', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000181EEB16570>, origin='c:\\repo\\jndr\\mark1\\zero2ai\\experiments\\..\\darth\\fn\\activation.py'),
 '__file__': 'c:\\repo\\jndr\\mark1\\zero2ai\\experiments\\..\\darth\\fn\\activation.py',
 '__cached__': 'c:\\repo\\jndr\\mark1\\zero2ai\\experiments\\..\\darth\\fn\\__pycache__\\activation.cpython-312.pyc',
 '__builtins__': {'__name__': 'builtins',
  '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but

In [53]:
fan_in, fan_out = 4, 2

seed = 21
np.random.seed(seed)
data = np.random.randn(4, fan_in)
print(f'data : \n{data}\n')

# l1 = Linear(fan_in, 3, activation=ReLU)
# l2 = Linear(3, 2)
# l3 = Linear(2, fan_out)

# o1 = l1.forward(data)
# o2 = l2.forward(o1)
# o3 = l3.forward(o2)

# s1 = Sequential(l1, l2, l3)
# out = s1.forward(data)

# print(f'out == o3 : {np.array_equal(out, o3)}')
# print(f'\nout : \n{out}')
# print(f'\no3 : \n{o3}')

data : 
[[-0.05196425 -0.11119605  1.0417968  -1.25673929]
 [ 0.74538768 -1.71105376 -0.20586438 -0.23457129]
 [ 1.12814404 -0.01262595 -0.61320029  1.3736885 ]
 [ 1.61099198 -0.68922827  0.69192371 -0.4481156 ]]



In [54]:
l1 = Linear(fan_in, 4, activation=av.sigmoid)
l2 = Linear(4, fan_out, activation=av.relu)
# l1.add_module('l2', l2)
l1

[Linear] kwargs {'activation': 'sigmoid'}
[Linear] update_kwargs called with activation: sigmoid
Getting activation function for name: sigmoid
Creating activation function: sigmoid
[Sigmoid] kwargs {}
[Sigmoid] update_kwargs called with activation: 
Getting activation function for name: 
[Sigmoid] Activation set to: None
[Linear] Activation set to: None
[Linear] kwargs {'activation': 'relu'}
[Linear] update_kwargs called with activation: relu
Getting activation function for name: relu
Creating activation function: relu


KeyError: 'relu'

In [ ]:
o1 = l1.forward(data)
o2 = l2.forward(o1)
print(f'\no1 : \n{o1}')
print(f'\no2 : \n{o2}')

[Linear] forward called
[Linear] _forward Linear called with input shape (4, 4)
[Linear] apply_activation called with activation: None
[Linear] forward called
[Linear] _forward Linear called with input shape (4, 4)
[Linear] apply_activation called with activation: None

o1 : 
[[0.80267875 0.32938475 0.44940278 0.47434047]
 [0.16651829 0.29038    0.30061828 0.5186003 ]
 [0.14031441 0.45884269 0.55349799 0.46444624]
 [0.29502398 0.16969145 0.44017911 0.48073256]]

o2 : 
[[1.99212329 0.2809689 ]
 [1.10456448 0.09544833]
 [1.16031054 0.        ]
 [1.1993418  0.28192194]]


In [ ]:
s = Sequential(
    Linear(fan_in, 4, activation=av.sigmoid),
    Linear(4, fan_out, activation=av.relu)
)
out = s.forward(data)
print(f'\nout : \n{out}')

[Linear] update_kwargs called with activation: Sigmoid
Creating activation function: Sigmoid


NameError: name '_activations' is not defined

In [ ]:
r.backward(1.2)

array([[0. , 0. , 1.2, 0. ],
       [1.2, 0. , 0. , 0. ],
       [1.2, 0. , 0. , 1.2],
       [1.2, 0. , 1.2, 0. ]])

# 🐛 Circular Dependency Analysis

Let's analyze and fix the circular imports in darth framework.

## Current Issues:
1. `darth.nn.layers` imports `Activation` from `darth.fn` (which doesn't exist)
2. `darth.fn.activation` imports `Module` from `darth.core`
3. Potential circular reference when Module tries to use activations

In [ ]:
# Let's test the current imports to see the exact error
try:
    print("Testing imports...")
    from darth.nn import Linear
    print("✅ Linear imported successfully")
    
    from darth.fn import av  
    print("✅ av imported successfully")
    
    # Try creating a Linear layer
    layer = Linear(4, 2, activation=av.sigmoid)
    print("✅ Linear layer created successfully")
    
except Exception as e:
    print(f"❌ Import error: {e}")
    print(f"Error type: {type(e).__name__}")
    import traceback
    traceback.print_exc()